# docker-compose.yml
version: '3'
services:
  data-collector:
    image: hyejiyu/cloudproject-data:latest
    volumes:
      - ./output:/app/output
    restart: always

  web-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./output:/app/output
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/accidents
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: